### ISSUE TITLE
[Feature Suggestion] Support connect by replica-set url.

### ISSUE THREAD

**Issue by Jeff-Tian** [mbahoshy/mongo-monkey#6]
Need support to connect mongo db by `mongodb://username:password@dds-xxx-pub.mongodb.rds.aliyuncs.com:3717,dds-yyy-pub.mongodb.rds.aliyuncs.com:3717/dbname?replicaSet=mgset-123`.

Current it fails:

![image](https://user-images.githubusercontent.com/3367820/72249195-d00d8380-3633-11ea-82eb-2b344601e13a.png)

```
[ERROR-ReplSet:26671] 1578911669296 [1] server in replset mgset-4016449 is not part of the specified setName mgset-4016449:/null { type: 'error',
  message:
   '[1] server in replset mgset-4016449 is not part of the specified setName mgset-4016449:/null',
  className: 'ReplSet',
  pid: 26671,
  date: 1578911669296 }

  MongoError: provided setName for Replicaset Connection does not match setName found in server seedlist
      at State.update (/Users/jefftian/.nvm/versions/node/v10.15.1/lib/node_modules/mongo-monkey/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset_state.js:629:32)
      at processNewServer (/Users/jefftian/.nvm/versions/node/v10.15.1/lib/node_modules/mongo-monkey/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:1453:27)
      at Server.<anonymous> (/Users/jefftian/.nvm/versions/node/v10.15.1/lib/node_modules/mongo-monkey/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:1514:46)
      at Object.onceWrapper (events.js:277:13)
      at Server.emit (events.js:189:13)
      at /Users/jefftian/.nvm/versions/node/v10.15.1/lib/node_modules/mongo-monkey/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:546:23
      at /Users/jefftian/.nvm/versions/node/v10.15.1/lib/node_modules/mongo-monkey/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:584:11
      at /Users/jefftian/.nvm/versions/node/v10.15.1/lib/node_modules/mongo-monkey/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/strategies/ping.js:264:5
      at commandCallback (/Users/jefftian/.nvm/versions/node/v10.15.1/lib/node_modules/mongo-monkey/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1161:9)
      at Callbacks.emit (/Users/jefftian/.nvm/versions/node/v10.15.1/lib/node_modules/mongo-monkey/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
      at Connection.messageHandler (/Users/jefftian/.nvm/versions/node/v10.15.1/lib/node_modules/mongo-monkey/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:295:23)
      at Socket.<anonymous> (/Users/jefftian/.nvm/versions/node/v10.15.1/lib/node_modules/mongo-monkey/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:285:22)
      at Socket.emit (events.js:189:13)
      at addChunk (_stream_readable.js:284:12)
      at readableAddChunk (_stream_readable.js:265:11)
      at Socket.Readable.push (_stream_readable.js:220:10)
```

**Comment by mbahoshy** [comment]
@Jeff-Tian Thanks for the heads up. I need to revisit this application and give it a major face lift. Will include a fix for the issue described
